"""Raise alerting module — SendGrid email + SerpAPI corroboration + Notion update."""
import os
import requests
from datetime import datetime

SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY", "")
SERPAPI_API_KEY = os.getenv("SERPAPI_API_KEY", "")
ALERT_EMAIL = os.getenv("ALERT_EMAIL", os.getenv("TO_EMAIL", ""))
FROM_EMAIL = os.getenv("FROM_EMAIL", "dealradar@dealradar.ai")

# Lazy-load SendGrid
try:
    import sendgrid
    from sendgrid.helpers.mail import Mail
    HAS_SENDGRID = bool(SENDGRID_API_KEY)
except ImportError:
    HAS_SENDGRID = False

# Module-level SendGrid client (lazy initialization for testability)
sg = None

def _get_sg_client():
    """Get or create the SendGrid client. Exposed for testing."""
    global sg
    if sg is None and HAS_SENDGRID:
        sg = sendgrid.SendGridAPIClient(api_key=SENDGRID_API_KEY)
    return sg


def check_serpapi(domain: str, company_name: str) -> bool:
    """Check SerpAPI for corroborating news. Fails open (returns False)."""
    if not SERPAPI_API_KEY:
        print("[WARN] SERPAPI_API_KEY not set — skipping corroboration check")
        return False

    try:
        params = {
            "q": f"{company_name} raised funding {datetime.now().year - 1} {datetime.now().year}",
            "api_key": SERPAPI_API_KEY,
            "engine": "google",
        }
        resp = requests.get("https://serpapi.com/search", params=params, timeout=10)
        data = resp.json()
        organic = data.get("organic_results", [])
        if organic:
            print(f"  [ALERT] SerpAPI corroboration found for {company_name}")
            return True
        return False
    except Exception as e:
        print(f"  [WARN] SerpAPI check failed: {e}")
        return False


def send_raise_alert_email(raise_event: dict) -> bool:
    """Send raise alert email via SendGrid. Returns True if sent."""
    if not HAS_SENDGRID:
        print("[WARN] SendGrid not configured — skipping raise alert email")
        print(f"  Alert preview: {raise_event.get('company_name', 'Unknown Company')} raised {raise_event.get('last_raise_amount', 'Unknown')}")
        return False

    if not ALERT_EMAIL:
        print("[WARN] ALERT_EMAIL not set — skipping raise alert email")
        return False

    client = _get_sg_client()
    company = raise_event["company_name"]
    amount = raise_event.get("last_raise_amount", "Unknown")
    vc = raise_event.get("vc_source", "Unknown")
    signal = raise_event.get("signal_score", 0)
    one_liner = raise_event.get("one_liner", "No description available.")
    domain = raise_event.get("domain", "")
    current_date = raise_event.get("current_date", "recently")

    subject = f"[DealRadar Alert] {company} raised {amount} — {vc}"
    html_content = f"""
    <html><body>
    <h2>[DealRadar Alert] {company} raised {amount}</h2>
    <p><strong>VC Source:</strong> {vc}</p>
    <p><strong>Signal Score:</strong> {signal}</p>
    <p><strong>Previous Raise:</strong> {raise_event.get('previous_date', 'Unknown')}</p>
    <p><strong>Current Raise:</strong> {current_date}</p>
    <p><strong>One-liner:</strong> {one_liner}</p>
    <p><a href="{domain}">{domain}</a></p>
    <hr>
    <p><em>Generated by DealRadar v2</em></p>
    </body></html>
    """

    message = Mail(
        from_email=FROM_EMAIL,
        to_emails=ALERT_EMAIL,
        subject=subject,
        html_content=html_content,
    )

    try:
        response = client.send(message)
        if response.status_code in (200, 201, 202):
            print(f"  [ALERT] Raise alert email sent for {company}")
            return True
        else:
            print(f"  [ERROR] SendGrid returned {response.status_code}")
            return False
    except Exception as e:
        print(f"  [ERROR] SendGrid send failed: {e}")
        return False

