# src/commander/digest.py
"""Weekly digest: Top 5 targets delivered via email to Steven."""
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import date

try:
    import sendgrid
    from sendgrid.helpers.mail import Mail
    HAS_SENDGRID = bool(os.getenv("SENDGRID_API_KEY"))
except ImportError:
    HAS_SENDGRID = False

SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("FROM_EMAIL", "")
SMTP_PASS = os.getenv("EMAIL_PASSWORD", "")
FROM_EMAIL = os.getenv("FROM_EMAIL", "dealradar@dealradar.ai")
TO_EMAIL = os.getenv("TO_EMAIL", "steven@inp-capital.com")


def format_top_companies(companies: list[dict]) -> str:
    """Format Top 5 companies as HTML for email."""
    rows = []
    for i, c in enumerate(companies, 1):
        tags = ", ".join(c.get("tags", []) or [])
        row = f"""
        <tr>
            <td>{i}</td>
            <td><a href="{c.get('domain', '')}">{c.get('company_name', '')}</a></td>
            <td>{c.get('signal_score', 0)}</td>
            <td>{c.get('vc_source', '')}</td>
            <td>{c.get('sector', 'Unknown')}</td>
            <td>{c.get('funding_clock', 'N/A')}</td>
            <td>{tags}</td>
        </tr>
        """
        rows.append(row)
    return "\n".join(rows)


class WeeklyDigest:
    """Generate and send weekly Top 5 deal targets digest email."""

    def __init__(self, top_n: int = 5):
        self.top_n = top_n

    def get_top_companies(self, companies: list[dict], top_n: int | None = None) -> list[dict]:
        """Return top N companies sorted by signal score descending."""
        n = top_n or self.top_n
        sorted_companies = sorted(companies, key=lambda c: c.get("signal_score", 0), reverse=True)
        return sorted_companies[:n]

    def build_html(self, companies: list[dict]) -> str:
        """Build HTML email body."""
        table_rows = format_top_companies(companies)
        today = date.today().isoformat()

        return f"""
        <html>
        <body>
        <h2>DealRadar Weekly Digest — {today}</h2>
        <p>Your top {len(companies)} deal targets this week, ranked by Signal Score.</p>

        <table border="1" cellpadding="8" cellspacing="0">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Company</th>
                    <th>Signal Score</th>
                    <th>VC Source</th>
                    <th>Sector</th>
                    <th>Funding Clock</th>
                    <th>Tags</th>
                </tr>
            </thead>
            <tbody>
                {table_rows}
            </tbody>
        </table>

        <p style="margin-top:20px">
        <em>Generated by DealRadar MVP — INP Capital</em>
        </p>
        </body>
        </html>
        """

    def send_email(self, companies: list[dict], subject: str | None = None) -> bool:
        """Send digest email via SMTP/SendGrid."""
        if not SMTP_USER or not SMTP_PASS:
            print("[WARN] SMTP credentials not configured. Skipping email send.")
            print(f"Digest preview:\n{self.build_html(companies)}")
            return False

        to = TO_EMAIL or os.getenv("TO_EMAIL", "")
        if not to:
            print("[WARN] TO_EMAIL not configured")
            return False

        subject = subject or f"DealRadar Weekly Digest — {date.today().isoformat()}"
        html_body = self.build_html(companies)

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = FROM_EMAIL
        msg["To"] = to
        msg.attach(MIMEText(html_body, "html"))

        if HAS_SENDGRID and os.getenv("SENDGRID_API_KEY"):
            try:
                sg = sendgrid.SendGridAPIClient(api_key=os.getenv("SENDGRID_API_KEY"))
                message = Mail(
                    from_email=FROM_EMAIL,
                    to_emails=to,
                    subject=subject,
                    html_content=html_body,
                )
                sg.send(message)
                print(f"  Digest sent to {to} via SendGrid")
                return True
            except Exception as e:
                print(f"  [WARN] SendGrid failed, falling back to SMTP: {e}")

        # Fallback: SMTP
        try:
            with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
                server.starttls()
                server.login(SMTP_USER, SMTP_PASS)
                server.send_message(msg)
            print(f"  Digest sent to {to} via SMTP")
            return True
        except Exception as e:
            print(f"  [ERROR] Failed to send email: {e}")
            return False

    def run(self, enriched_companies_path: str = "data/enriched_companies.json") -> bool:
        """Load enriched companies, generate digest, send email."""
        import json
        with open(enriched_companies_path) as f:
            companies = json.load(f)

        top5 = self.get_top_companies(companies)
        print(f"\nTop {len(top5)} targets this week:")
        for c in top5:
            print(f"  [{c['signal_score']}] {c['company_name']} — {c.get('vc_source', '')}")

        return self.send_email(top5)
